## Code fourni pour lire les binaires:

In [30]:
import matplotlib.pyplot as plt
import numpy as np
import time

def read_int(f):
    ba = bytearray(4)
    f.readinto(ba)
    prm = np.frombuffer(ba, dtype=np.int32)
    return prm[0]

def read_double(f):
    ba = bytearray(8)
    f.readinto(ba)
    prm = np.frombuffer(ba, dtype=np.double)
    return prm[0]

def read_double_tab(f, n):
    ba = bytearray(8*n)
    nr = f.readinto(ba)
    if nr != len(ba):
        return []
    else:
        prm = np.frombuffer(ba, dtype=np.double)
        return prm

def get_pics_from_file(filename):
    # Lecture du fichier d'infos + pics detectes (post-processing KeyFinder)
    #print("Ouverture du fichier de pics "+filename)
    f_pic = open(filename, "rb")
    info = dict()
    info["nb_pics"] = read_int(f_pic)
    #print("Nb pics par trame: " + str(info["nb_pics"]))
    info["freq_sampling_khz"] = read_double(f_pic)
    #print("Frequence d'echantillonnage: " + str(info["freq_sampling_khz"]) + " kHz")
    info["freq_trame_hz"] = read_double(f_pic)
    #print("Frequence trame: " + str(info["freq_trame_hz"]) + " Hz")
    info["freq_pic_khz"] = read_double(f_pic)
    #print("Frequence pic: " + str(info["freq_pic_khz"]) + " kHz")
    info["norm_fact"] = read_double(f_pic)
    #print("Facteur de normalisation: " + str(info["norm_fact"]))
    tab_pics = []
    pics = read_double_tab(f_pic, info["nb_pics"])
    nb_trames = 1
    while len(pics) > 0:
        nb_trames = nb_trames+1
        tab_pics.append(pics)
        pics = read_double_tab(f_pic, info["nb_pics"])
    #print("Nb trames: " + str(nb_trames))
    f_pic.close()
    return tab_pics, info

    """
    ######### Pics ############
    # NO KEY
    plt.figure(1)
    plt.subplot(211)
    plt.plot(range(1,info["nb_pics"]+1), np.mean(pics_nokey,axis=0), 'ko')
    plt.xlabel('numéro de pic')
    plt.ylabel('valeur du pic')
    plt.title('no key')
    plt.ylim(0, 1.5)
    plt.grid(b=True, which='both')
    # PAD-0
    plt.subplot(212)
    plt.plot(range(1,info["nb_pics"]+1), pics_nokey[0], 'ko')
    plt.xlabel('numéro de pic')
    plt.ylabel('valeur du pic')
    plt.title('PAD-0')
    plt.ylim(0, 1.5)
    plt.grid(b=True, which='both')
    #
    plt.show()
    """

# Notre Algorithme
* Enlever le bruit en faisant - Nokey ------- Inutile ?
* Séparer les trames en chunk ------- While == précédent + [un certain pas]
* Attention à shift+a par exemple --- Maybe in top best letters ?
* ctrl alt suppr au début ---- Histoire de pas oublier

### Bin to png

In [ ]:
#for file in glob.glob("../data/pics_*.bin"):
 #   key = file.split("pics_")[1].replace(".bin","")
 #   values, info = get_pics_from_file(file)
 #   plt.imshow(values,aspect="auto",)
 #   plt.savefig("../data/PNGs/pics_" + key + ".png")

### Bibliothèques utilisées :

In [31]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix,f1_score,accuracy_score
import glob

## Constitution du dataset

In [ ]:
# Il faut enlever le bruit

X,Y = [],[]

pics_nokey, info = get_pics_from_file("../data/pics_NOKEY.bin")

i = 0
for file in glob.glob("../data/pics_*.bin"):
    key = file.split("pics_")[1].replace(".bin","")
    if key == "LOGINMDP" or key == "NOKEY":
        continue
    values, info = get_pics_from_file(file)
    for frame in values:
        X.append(frame)
        Y.append(key)

    i += 1
    if i == 3:
        break
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2)

# Scaling des données
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [4]:
X,Y = [],[]

pics_nokey, info = get_pics_from_file("../data/pics_NOKEY.bin")

i = 0
for file in glob.glob("../data/pics_*.bin"):
    key = file.split("pics_")[1].replace(".bin","")
    if key == "LOGINMDP" or key == "NOKEY":
        continue
    values, info = get_pics_from_file(file)
    for frame in values:
        X.append(frame)
        Y.append(key)

    i += 1
    if i == 3:
        break
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2)

# Scaling des données
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

### KNN Algorithm

In [68]:
import math
# Best value for N (internet said this)
N = math.floor(math.sqrt(len(Y_test)))
if N % 2 == 0:
    N -= 1

# KNN Clustering
classifier = KNeighborsClassifier(n_neighbors=N, p=2, metric='euclidean',n_jobs=-1)
classifier.fit(X_train,Y_train)
Y_pred = classifier.predict(X_test)
Y_pred

array(['D', '5', '0', '5', 'A', '0', 'F', 'SUPPR', '5', 'P', '5', '5',
       '0', 'P', 'E', '7', '0', 'P', 'D', 'E', '5', 'A', 'A', 'SUPPR',
       'ENTER', 'D', '0', '7', '5', 'H', 'A', 'CTRL', 'Z', 'A', '0', '5',
       'A', '5', '0', 'P', 'A', 'SUPPR', 'E', 'P', 'Y', 'D', 'D', '5',
       '5', 'W', 'W', 'A', 'P', '0', 'P', 'P', '5', 'D', 'A', '7',
       'ENTER', '0', 'H', '0', 'F', '0', 'F', '0', '0', '3', 'M', 'W',
       'A', 'F', 'P', 'A', 'A', 'H', 'P', '0', 'P', 'A', 'SUPPR', '0',
       'D', 'SPACE', '5', '0', 'P', 'SHIFT', 'SHIFT', 'P', 'SUPPR', '0',
       'W', '0', '5', 'P', 'A', '0', '0', '0', 'A', 'ENTER', 'D', '1',
       '0', 'SUPPR', '5', '3', 'D', 'E', 'D', 'CTRL', 'SUPPR', '5', 'A',
       'SUPPR', 'E', 'P', 'A', 'SUPPR', 'A', 'A', '0', 'CTRL', '5', '0',
       '0', 'SUPPR', '0', 'A', 'A', '5', '0', '3', 'A', '0', '3', 'SUPPR',
       'P', 'P', 'W', '5', 'ENTER', 'SHIFT', 'D', '0', 'P', 'P', 'SUPPR',
       'ENTER', '5', '5', 'D', 'F', 'P', 'E', 'P', 'D', 'A', 'ENT

### Evaluate Model

In [69]:
cm = confusion_matrix(Y_test,Y_pred)
# La diagonale c'est les bons guess et le reste les fautes
print(cm)
print(accuracy_score(Y_test,Y_pred),"%")


[[0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 1]
 [2 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]]
0.06707317073170732 %
